# Enhanced Prometheus Configuration for Fresh Supply Chain Intelligence System
# Production-ready monitoring with comprehensive metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fresh-supply-chain'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "rules/api_alerts.yml"
  - "rules/infrastructure_alerts.yml"
  - "rules/business_alerts.yml"
  - "rules/ml_model_alerts.yml"
  - "rules/sla_alerts.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Enhanced scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Fresh Supply Chain API (Enhanced)
  - job_name: 'fresh-supply-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'api_.*'
        target_label: component
        replacement: 'api'

  # Fresh Supply Chain Dashboard
  - job_name: 'fresh-supply-dashboard'
    static_configs:
      - targets: ['dashboard:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SQL Server with enhanced metrics
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver-exporter:9399']
    scrape_interval: 30s
    scrape_timeout: 15s
    params:
      collect[]:
        - mssql_connections
        - mssql_deadlocks
        - mssql_user_settable
        - mssql_waitstats
        - mssql_database_io
        - mssql_memory_clerks
        - mssql_buffer_manager
        - mssql_os_performance_counters

  # Redis with comprehensive metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      check-keys: ['*']
      check-single-keys: ['cache:*', 'session:*', 'rate_limit:*']

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker containers monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Nginx/Load Balancer metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    scrape_timeout: 15s

  # Jaeger tracing metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom ML Model metrics
  - job_name: 'ml-models'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/models'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Business metrics (custom endpoint)
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/business'
    scrape_interval: 300s  # 5 minutes
    scrape_timeout: 30s

  # Celery worker metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9540']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api:8000/health
        - http://dashboard:3000/
        - http://grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration for long-term storage
remote_write:
  - url: "http://cortex:9009/api/prom/push"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration
remote_read:
  - url: "http://cortex:9009/api/prom/read"
    read_recent: true