# Prometheus configuration for Fresh Supply Chain Intelligence System
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Fresh Supply Chain API
  - job_name: 'fresh-supply-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Fresh Supply Chain Dashboard
  - job_name: 'fresh-supply-dashboard'
    static_configs:
      - targets: ['dashboard:8050']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # SQL Server (if using SQL Server Exporter)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver-exporter:1433']
    scrape_interval: 30s

  # Redis (if using Redis Exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:6379']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s