apiVersion: v1
kind: Namespace
metadata:
  name: fresh-supply-chain
  labels:
    name: fresh-supply-chain
    environment: production
    app: fresh-supply-chain-intelligence
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fresh-supply-chain-quota
  namespace: fresh-supply-chain
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fresh-supply-chain-limits
  namespace: fresh-supply-chain
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim